### ISSUE TITLE
Changing the standard format's timestamp format from Unix to ISO 8601

### ISSUE THREAD

**Issue by quinn-dev** [andrew-sayers/sleep-diary-formats#2]
### The problem:
The standard format currently uses Unix Epoch timestamps, which have a couple of significant disadvantages.
#### 1. They are not human-readable
The integer used by Unix timestamps cannot be read by humans without an utility to convert it to a conventional time and date.
Other than the `duration` field (which I hope to address in another issue), every field of the format is human-readable, and I think that's a useful property we should aim to keep.
#### 2. Unix timestamps require documentation
Unix timestamps are not standardized. Some representations describe the time passed since January 1st 1970 as seconds, others as milliseconds. This can lead to confusion and implementation errors of all sorts.

Ideally, the standard format should use a human-readable, self-documenting, unambiguous, standardized timestamp format.

### The solution:
ISO 8601 to the rescue.

ISO 8601 is a standardized, widely used timestamp format. Some of its advantages include:
- it's human-readable (someone can look at them and understand the date and time)
- it's standardized and self-documenting (no additional documentation required, no room for implementation errors)
- it's supported by pretty much every modern programming language (either directly as part of the language or as a standard library)
- can also represent the time zone of an event
- natively supported in JavaScript

The only downsides to ISO 8601 I could think of are:
- it takes up slightly more storage (which shouldn't be an issue for the scope of this format)
- it's harder to implement an ISO 8601 converter from scratch compared to Unix timestamps that can be calculated quite easily (but since pretty much every language supports ISO 8601 timestamps either natively or through standard libraries, this shouldn't be a problem)

Since ISO 8601 also incorporates the time zone of the event, I see no reason to keep `start_timezone` and `end_timezone`. This way a developer can directly parse the timestamp and use the utilities provided by most programming languages to evaluate the data.

I'll try and work on a PR within the next few days, and I'm open to any arguments in favor of Unix timestamps.

**Comment by andrew-sayers** [comment]
To be honest, I'm not convinced about this.  A few questions spring to mind:

* how would you do maths with string dates?  This seems like it will increase the complexity of stats code (and therefore probability of bugs), in order to decrease the complexity of code that's less inherently complex
* this seems like the wrong approach from an MVC perspective - if the data is hard to view, we should make another view rather than changing the model
* numeric offsets lose information compared to string offsets.  For example, Daylight Savings Time falls on different dates in diffent places with the same numeric timezone

Surely programs will want to display dates in their own way no matter what we do (e.g. with locale-specific dates or a clock or something), and developers will just use made-up timestamps (e.g. `123456789`)?  Could you give an example use case for string dates?

**Comment by quinn-dev** [comment]
1. How would you do math with string dates?
I wouldn't, I would consider it bad practice. Unless you are implementing date/time functionality from scratch and you know exactly what you're doing, you should not handle dates and times. There are many things to take into account when doing Math with dates, and in most cases you are better off using a standard library for date/time to outsource date-related calculations, like the time difference between two timestamps. If you need to do more complicated Math, you can use your date/time library to conduct date/time-related calculations (such as the difference between two timestamps), and use the numeric result to feed your more complicated mathematical functions.

2. this seems like the wrong approach from an MVC perspective - if the data is hard to view, we should make another view rather than changing the model
From my perspective, the question is whether the data needs to be hard to view. In this case, I don't see any reason to make it harder for the user to understand the format.

3. numeric offsets lose information compared to string offsets
That's a good point, so we won't be able to get rid of the `_timezone` fields.

In the end, I still think ISO 8601 dates have a few advantages that Unix timestamps don't:
- standardized (Unix timestamps are not and require documentation)
- unambiguous (Unix timestamp implementations can vary a lot, ISO 8601 implementations don't)

I don't see any immediate "use cases" for either. Both need to be parsed by a time/date library first to become useful. Only Unix timestamps leave so much room for errors, while ISO timestamps don't.

**Comment by andrew-sayers** [comment]
The thing is, this is a date/time library for people with non-standard concepts of date and time.  For example, imagine you want to calculate the number of days between `2020-01-01T00:00.000Z` and `2020-02-01T00:00.000Z`.  A normal date library will tell you the answer is 31, someone with a 48-hour day will tell you the answer is 15.5, and someone with polyphasic sleep will say "what's a day?".  To put it another way, the "unreadability" of Unix timestamps is a actually a feature that stops people from misreading values as having a well-defined relationship to a 24-hour clock.

A good example of the problem might be [the way records are built in Standard format](/andrew-sayers/sleep-diary-formats/blob/main/src/Standard/format.js#L248).  There's a fairly complex process for calculating "days" while accomodating different day lengths, missing records and so on.  Any new solution would need to solve that (and all the other problems in that file) somehow.

**Comment by quinn-dev** [comment]
While I still think that using ISO 8601 is more explicit and less error-prone, I see that there are many use cases which benefit from Unix epoch time, especially for projects related to circadian sleep rhythm disorders. In other words, I'm convinced that changing the standard format to ISO 8601 isn't necessarily a beneficial change.
